name: app
version: 0.1.0
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  bridge:
    git:
      url: https://github.com/dart-bridge/framework.git
      ref: develop
  sass: "^0.4.2"
  markdown: "^0.8.0"
  js: "^0.6.0"
  yaml: "^2.1.7"
  slugify: "^0.1.1"
  intl: "^0.12.4+2"
dev_dependencies:
  test: any
  grinder: any
transformers:
    - sass
