name: app
version: 0.1.0
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  bridge: '^1.0.0-beta.1'
  sass: "^0.4.2"
  markdown: "^0.8.0"
  js: ^0.6.0-beta
dev_dependencies:
  test: any
  grinder: any
transformers:
    - sass
